### ISSUE TITLE
Tag newest release

### ISSUE THREAD

**Issue by spawnia** [usr42/docker-cifs#1]
Hi, thanks for this nice and simple image. I like images of that kind,
sometimes all the magic other people put in is just to much.

Can you tag the latest `v0.3` so i can use a fixed version in my CI pipeline?

**Comment by usr42** [comment]
Thanks for the feedback.
The newest commit was just a change in the readme and should not change the image itself (besides possible updates in of the alpine packages). I've added the `v0.3` tag.

Cheers
